apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: 
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-nodeport
  namespace: 
  labels:
    app: website
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: website
